---
abstract: 'Perl module for HTTP JSON output for structured errors.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Pure-HTTP-JSON
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Error::Pure::Output::JSON: 0.01
  Error::Pure::Utils: 0.11
  Exporter: 0
  List::MoreUtils: 0
  Readonly: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Error-Pure-HTTP-JSON
  homepage: https://github.com/tupinek/Error-Pure-HTTP-JSON
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Error-Pure-HTTP-JSON
version: 0.03
