---
abstract: 'Perl module for HTTP JSON output for structured errors.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Pure-HTTP-JSON
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Error::Pure::Output::JSON: 0.01
  Error::Pure::Utils: 0.11
  Exporter: 0
  List::MoreUtils: 0
  Readonly: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Error-Pure-HTTP-JSON/issues
  homepage: https://github.com/michal-josef-spacek/Error-Pure-HTTP-JSON
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Error-Pure-HTTP-JSON
version: '0.06'
